"""Add default_break to employee

Revision ID: 90d40742f620
Revises: 8b92ec97ac5c
Create Date: 2025-07-07 16:25:22.580663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d40742f620'
down_revision = '8b92ec97ac5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('default_break', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.String(length=10), nullable=False),
    sa.Column('p_type', sa.String(length=3), nullable=False),
    sa.Column('ts', sa.String(length=19), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    op.drop_table('employee')
    # ### end Alembic commands ###
